import type { Holding, Listing } from "./types";

// Demo dataset — a manually-curated directory (product doc §10, open question 2:
// "manual is the honest v1 answer, and it caps the directory at 30–50 listings").
// Disclosure is deliberately uneven across listings: most fields are empty for
// most listings, because that's the real shape of the problem Assay reports on
// (product doc §2). Nothing here should read as a real, currently operating
// issuer — names, docs links and figures are illustrative.

export const listings: Listing[] = [
  {
    id: "meridian-treasury-fund",
    name: "Meridian Treasury Fund",
    issuer: "Meridian Capital",
    assetClass: "U.S. Treasuries",
    chain: "Ethereum",
    yieldPct: 4.8,
    minInvestmentUsd: 500,
    feesBps: 25,
    description:
      "Tokenized claim on a short-duration U.S. Treasury bill ladder, rebalanced weekly.",
    docsUrl: "https://meridian-capital.example/docs/treasury-fund",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-09-01",
      cycleDays: 7,
      verifier: "Halden Fund Services (independent administrator)",
      method: "Custodian statement reconciliation against on-chain supply",
      scope: "Existence and face value of the underlying T-bill ladder",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 1, maxDays: 3 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates in-app" },
        { label: "T-bill ladder position unwound", trigger: "Next business day settlement window" },
        { label: "USDC settlement to holder wallet", trigger: "Confirmed unwind, T+1 to T+3" },
      ],
    },
    secondaryMarket: { available: true, depth: "deep", venue: "Meridian AMM pool + 2 listed DEXs" },
    reserveTransparency: "available",
  },
  {
    id: "vantage-short-duration-treasury",
    name: "Vantage Short Duration Treasury",
    issuer: "Vantage Digital Assets",
    assetClass: "U.S. Treasuries",
    chain: "Base",
    yieldPct: 4.6,
    minInvestmentUsd: 100,
    feesBps: 20,
    description: "Daily-rolled overnight Treasury repo exposure, tokenized 1:1.",
    docsUrl: "https://vantage-digital.example/products/short-duration",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-09-03",
      cycleDays: 1,
      verifier: "Meraux & Co (auditor)",
      method: "Daily NAV attestation published on-chain",
      scope: "Existence of underlying repo collateral",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 1, maxDays: 1 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates in-app, before 2pm ET cutoff" },
        { label: "USDC settlement to holder wallet", trigger: "Same business day" },
      ],
    },
    secondaryMarket: { available: true, depth: "deep", venue: "3 listed DEXs" },
    reserveTransparency: "available",
  },
  {
    id: "harbor-yield-notes",
    name: "Harbor Yield Notes",
    issuer: "Harbor Street Capital",
    assetClass: "Private credit",
    chain: "Base",
    yieldPct: 11.2,
    minInvestmentUsd: 5000,
    feesBps: 150,
    description: "Senior secured notes backed by a pool of SME working-capital loans.",
    docsUrl: "https://harborstreet.example/notes",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-06-22",
      cycleDays: 30,
      verifier: "Harbor Street Capital (self-attested)",
      method: "Issuer-published loan tape, unaudited",
      scope: "Existence of the underlying loan pool",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 60, maxDays: 180 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates, quarterly window only" },
        { label: "Loan pool positions called or sold down", trigger: "Next scheduled quarterly window" },
        { label: "Settlement to holder wallet", trigger: "Within 30 days of window close" },
      ],
    },
    secondaryMarket: { available: true, depth: "thin", venue: "1 listed DEX, low volume" },
    reserveTransparency: "not_disclosed",
  },
  {
    id: "ironclad-bridge-lending",
    name: "Ironclad Bridge Lending",
    issuer: "Ironclad Capital Partners",
    assetClass: "Private credit",
    chain: "Polygon",
    yieldPct: 13.5,
    minInvestmentUsd: 10000,
    feesBps: 200,
    description: "Short-duration bridge loans to commercial real estate sponsors.",
    docsUrl: "https://ironclad-partners.example/bridge-lending",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-07-06",
      cycleDays: 45,
      verifier: "Ironclad Capital Partners (self-attested)",
      method: "Issuer-published borrower schedule, unaudited",
      scope: "Existence of the underlying loan book",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 90, maxDays: 270 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates, subject to available liquidity" },
        { label: "Matched against new subscriptions or loan payoffs", trigger: "Ongoing, no fixed window" },
        { label: "Settlement to holder wallet", trigger: "Within 30 days of match" },
      ],
    },
    secondaryMarket: { available: true, depth: "thin", venue: "1 listed DEX, low volume" },
    reserveTransparency: "not_disclosed",
  },
  {
    id: "cobalt-reserve-gold",
    name: "Cobalt Reserve Gold",
    issuer: "Cobalt Bullion Trust",
    assetClass: "Commodities",
    chain: "Polygon",
    yieldPct: null,
    minInvestmentUsd: 250,
    feesBps: 40,
    description: "1 token = 1 gram of allocated, vaulted gold in a Zurich freeport.",
    docsUrl: "https://cobalt-bullion.example/gold",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-08-26",
      cycleDays: 30,
      verifier: "Bureau Veritas (independent inspector)",
      method: "Physical bar-count audit against vault manifest",
      scope: "Existence and allocation of the underlying gold bars",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 5, maxDays: 14 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder chooses cash-out or physical delivery" },
        { label: "Vault release authorized", trigger: "Within 3 business days" },
        { label: "Cash settlement or physical shipment", trigger: "5–14 days depending on delivery method" },
      ],
    },
    secondaryMarket: { available: true, depth: "moderate", venue: "2 listed DEXs" },
    reserveTransparency: "available",
  },
  {
    id: "meridian-silver-vault",
    name: "Meridian Silver Vault",
    issuer: "Meridian Capital",
    assetClass: "Commodities",
    chain: "Solana",
    yieldPct: null,
    minInvestmentUsd: 100,
    feesBps: null,
    description: "1 token = 10 ounces of vaulted silver, custody location undisclosed.",
    docsUrl: "https://meridian-capital.example/silver",
    verification: { kind: "not_disclosed" },
    redemption: { disclosed: false },
    secondaryMarket: { available: true, depth: "unknown", venue: "1 listed DEX" },
    reserveTransparency: "available",
  },
  {
    id: "solace-trade-finance-pool",
    name: "Solace Trade Finance Pool",
    issuer: "Solace Markets",
    assetClass: "Trade finance",
    chain: "Solana",
    yieldPct: 9.4,
    minInvestmentUsd: 1000,
    feesBps: 125,
    description: "Pooled exposure to short-term invoice factoring for import/export SMEs.",
    docsUrl: "https://solace-markets.example/trade-finance",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-07-26",
      cycleDays: 60,
      verifier: "Solace Markets (self-attested)",
      method: "Issuer-published invoice ledger, unaudited",
      scope: "Existence of the underlying invoice pool",
    },
    redemption: { disclosed: false },
    secondaryMarket: { available: true, depth: "thin", venue: "1 listed DEX, low volume" },
    reserveTransparency: "not_disclosed",
  },
  {
    id: "alder-street-residences",
    name: "Alder Street Residences",
    issuer: "Alder Street REIT",
    assetClass: "Real estate",
    chain: "Ethereum",
    yieldPct: 6.1,
    minInvestmentUsd: 2500,
    feesBps: 100,
    description: "48-unit multifamily property in Columbus, OH, tokenized as fractional equity.",
    docsUrl: "https://alderstreet-reit.example/residences",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-08-14",
      cycleDays: 90,
      verifier: "Cortland Title & Escrow (independent title company)",
      method: "Title search + county recorder cross-check",
      scope: "Unencumbered title held by the issuing SPV",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 90, maxDays: 180 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates, quarterly window only" },
        { label: "Property appraisal refreshed", trigger: "Within 30 days of window open" },
        { label: "Buyout funded from reserve or new subscriptions", trigger: "Within 60 days of appraisal" },
      ],
    },
    secondaryMarket: { available: true, depth: "thin", venue: "1 listed DEX, low volume" },
    reserveTransparency: "available",
    costReserve: {
      disclosed: true,
      reserveBalanceUsd: 184000,
      monthlyKnownExpensesUsd: 21000,
      upcomingExpenses: [
        { label: "Property tax installment", date: "2026-11-15", amountUsd: 38000 },
        { label: "Insurance renewal", date: "2027-01-10", amountUsd: 26500 },
        { label: "Roof reserve assessment", date: "2027-03-01", amountUsd: 12000 },
      ],
      fundingSource: "rental_income",
      negativeMonthPlan:
        "A cash-flow-negative month is covered first from the property reserve; if the reserve would drop below 2 months of expenses, the SPV draws on its $150,000 issuer-backstop credit line before any capital call is considered.",
      legalEntity: "Alder Street Residences SPV LLC (Delaware)",
    },
  },
  {
    id: "union-square-retail-center",
    name: "Union Square Retail Center",
    issuer: "Union Square Holdings",
    assetClass: "Real estate",
    chain: "Base",
    yieldPct: 5.4,
    minInvestmentUsd: 5000,
    feesBps: 110,
    description: "Anchor-tenant retail center tokenized as fractional equity, single asset.",
    docsUrl: "https://unionsquare-holdings.example/retail-center",
    verification: {
      kind: "attested",
      lastVerifiedAt: "2026-08-02",
      cycleDays: 90,
      verifier: "Cortland Title & Escrow (independent title company)",
      method: "Title search + county recorder cross-check",
      scope: "Unencumbered title held by the issuing SPV",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 120, maxDays: 240 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates, semi-annual window only" },
        { label: "Property appraisal refreshed", trigger: "Within 45 days of window open" },
        { label: "Buyout funded from reserve or new subscriptions", trigger: "Within 90 days of appraisal" },
      ],
    },
    secondaryMarket: { available: false },
    reserveTransparency: "available",
    costReserve: {
      disclosed: true,
      reserveBalanceUsd: 61000,
      monthlyKnownExpensesUsd: 34000,
      upcomingExpenses: [
        { label: "Property tax installment", date: "2026-10-01", amountUsd: 54000 },
        { label: "CAM reconciliation payout to tenants", date: "2026-12-15", amountUsd: 18000 },
      ],
      fundingSource: "rental_income",
      negativeMonthPlan:
        "Anchor tenant rent covers ~92% of a typical month's carrying costs; a shortfall month is covered from the reserve. The reserve currently covers under 2 months of known expenses — the issuer has not disclosed a backstop beyond the reserve itself.",
      legalEntity: "Union Square Retail Center SPV LLC (Delaware)",
    },
  },
  {
    id: "northgate-logistics-portfolio",
    name: "Northgate Logistics Portfolio",
    issuer: "Northgate Industrial",
    assetClass: "Real estate",
    chain: "Avalanche",
    yieldPct: 7.2,
    minInvestmentUsd: 2500,
    feesBps: 95,
    description: "Three-property last-mile logistics portfolio, tokenized as fractional equity.",
    docsUrl: "https://northgate-industrial.example/logistics-portfolio",
    verification: {
      kind: "pending",
      pendingSince: "2026-08-23",
      verifier: "Cortland Title & Escrow (independent title company)",
      method: "Title search + county recorder cross-check",
      scope: "Unencumbered title held by the issuing SPV",
    },
    redemption: {
      disclosed: true,
      range: { minDays: 90, maxDays: 270 },
      steps: [
        { label: "Redemption request submitted", trigger: "Holder initiates, quarterly window only" },
        { label: "Portfolio appraisal refreshed", trigger: "Within 60 days of window open" },
        { label: "Buyout funded from reserve or new subscriptions", trigger: "Within 90 days of appraisal" },
      ],
    },
    secondaryMarket: { available: false },
    reserveTransparency: "not_disclosed",
    costReserve: { disclosed: false },
  },
  {
    id: "birchwood-multifamily",
    name: "Birchwood Multifamily",
    issuer: "Birchwood Property Group",
    assetClass: "Real estate",
    chain: "Polygon",
    yieldPct: 8.9,
    minInvestmentUsd: 1000,
    feesBps: 90,
    description: "120-unit garden-style apartment complex in Phoenix, AZ.",
    docsUrl: "https://birchwood-pg.example/multifamily",
    verification: {
      kind: "flagged",
      flaggedAt: "2026-08-30",
      reason: "Title encumbrance discrepancy reported by a third-party auditor, unresolved",
      verifier: "Third-party audit (walk-in report)",
      method: "Title search",
    },
    redemption: { disclosed: false },
    secondaryMarket: { available: true, depth: "thin", venue: "1 listed DEX, low volume" },
    reserveTransparency: "not_disclosed",
    costReserve: { disclosed: false },
  },
  {
    id: "cascade-timberland-trust",
    name: "Cascade Timberland Trust",
    issuer: "Cascade Land Co.",
    assetClass: "Real estate",
    chain: "Ethereum",
    yieldPct: 4.2,
    minInvestmentUsd: 500,
    feesBps: null,
    description: "Managed timberland acreage in the Pacific Northwest, tokenized as fractional equity.",
    docsUrl: "https://cascade-landco.example/timberland-trust",
    verification: { kind: "not_disclosed" },
    redemption: { disclosed: false },
    secondaryMarket: { available: true, depth: "unknown", venue: "1 listed DEX" },
    reserveTransparency: "not_disclosed",
    costReserve: { disclosed: false },
  },
];

export function getListing(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

// Existing-holder persona (product doc §3, secondary user + §5.8 portfolio).
export const holdings: Holding[] = [
  { listingId: "meridian-treasury-fund", units: 4200, costBasisUsd: 4200, acquiredAt: "2026-02-11" },
  { listingId: "harbor-yield-notes", units: 12, costBasisUsd: 12000, acquiredAt: "2026-01-04" },
  { listingId: "ironclad-bridge-lending", units: 3, costBasisUsd: 30000, acquiredAt: "2025-11-20" },
  { listingId: "birchwood-multifamily", units: 6, costBasisUsd: 6000, acquiredAt: "2025-09-02" },
];
